const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "/api";

export interface WebsiteConfig {
  id: string;
  name: string;
  mood: string;
  bestUseCase: string;
  conversionFocus: string;
  fontPair: string;
  palette: string[];
  qualityScore: number;
  html: string;
}

export async function generateWebsiteVariations(
  prompt: string,
): Promise<WebsiteConfig[]> {
  try {
    const response = await fetch(`${API_BASE_URL}/generate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ prompt }),
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();

    // Type guard to ensure data has variations property
    if (
      data &&
      typeof data === "object" &&
      "variations" in data &&
      Array.isArray(data.variations)
    ) {
      return data.variations.map((variation, index) => ({
        id: variation.id || `var-${index + 1}`,
        name: variation.name || `Website Variation ${index + 1}`,
        mood: variation.mood || "Modern",
        bestUseCase: variation.bestUseCase || "Business Website",
        conversionFocus: variation.conversionFocus || "Lead Generation",
        fontPair: variation.fontPair || "Inter / System",
        palette: variation.palette || ["#06b6d4", "#8b5cf6"],
        qualityScore:
          variation.qualityScore || 85 + Math.floor(Math.random() * 15),
        html:
          variation.html ||
          generateFallbackHTML(variation.title || `Website ${index + 1}`),
      }));
    }

    throw new Error("Invalid response format");
  } catch (error) {
    console.error("AI Generation failed:", error);
    return getFallbackVariations();
  }
}

function generateFallbackHTML(title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        brand: {
                            cyan: '#06b6d4',
                            purple: '#8b5cf6'
                        }
                    }
                }
            }
        }
    </script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
</head>
<body class="bg-black text-white font-inter">
    <div class="min-h-screen flex items-center justify-center">
        <div class="text-center max-w-2xl mx-auto px-6">
            <h1 class="text-6xl font-black mb-6 bg-linear-to-r from-brand-cyan to-brand-purple bg-clip-text text-transparent">
                ${title}
            </h1>
            <p class="text-xl text-white/60 mb-8">
                Premium website generated by VoiceToWebsite.com
            </p>
            <div class="glass p-8 rounded-3xl border border-white/10">
                <p class="text-white/40">
                    AI Generation Limited - Full version available after upgrade
                </p>
            </div>
        </div>
    </div>
    <div class="fixed bottom-4 right-4 text-xs text-white/20">
        VoiceToWebsite.com
    </div>
</body>
</html>`;
}

function getFallbackVariations(): WebsiteConfig[] {
  return [
    {
      id: "fallback-1",
      name: "Modern Professional",
      mood: "Cinematic Premium",
      bestUseCase: "Business Website",
      conversionFocus: "Lead Generation",
      fontPair: "Inter / System",
      palette: ["#06b6d4", "#1e40af"],
      qualityScore: 92,
      html: generateFallbackHTML("Modern Professional"),
    },
    {
      id: "fallback-2",
      name: "Creative Bold",
      mood: "Bold Experimental",
      bestUseCase: "Portfolio Website",
      conversionFocus: "Showcase",
      fontPair: "Space Grotesk / Inter",
      palette: ["#8b5cf6", "#ec4899"],
      qualityScore: 89,
      html: generateFallbackHTML("Creative Bold"),
    },
    {
      id: "fallback-3",
      name: "Clean Minimal",
      mood: "Clean Conversion",
      bestUseCase: "SaaS Product",
      conversionFocus: "Sign-ups",
      fontPair: "Inter / System",
      palette: ["#10b981", "#064e3b"],
      qualityScore: 95,
      html: generateFallbackHTML("Clean Minimal"),
    },
  ];
}
