export interface NavigationItem {
  href: string;
  label: string;
}

export const SHARED_NAV_ITEMS: NavigationItem[] = [
  { href: "/", label: "Home" },
  { href: "/features", label: "Features" },
  { href: "/how-it-works", label: "How It Works" },
  { href: "/demo", label: "Demo" },
  { href: "/pricing", label: "Pricing" },
  { href: "/store", label: "Store" },
  { href: "/appstore", label: "App Store" },
  { href: "/blog", label: "Blog" },
  { href: "/livestream", label: "Livestream" },
  { href: "/support", label: "Support" },
  { href: "/contact", label: "Contact" },
  { href: "/about", label: "About" },
  { href: "/status", label: "Status" },
  { href: "/search", label: "Search" },
  { href: "/gallery", label: "Gallery" },
  { href: "/templates", label: "Templates" },
  { href: "/partners", label: "Partners" },
  { href: "/trust", label: "Trust Center" },
  { href: "/referrals", label: "Referrals" },
  { href: "/projects", label: "Projects" },
  { href: "/the3000", label: "The3000" },
  { href: "/studio3000", label: "Studio3000" },
  { href: "/webforge", label: "Webforge" },
  { href: "/cursor-demo", label: "Cursor Demo" },
  { href: "/sandbox", label: "Sandbox" },
  { href: "/license", label: "License" },
  { href: "/privacy", label: "Privacy" },
  { href: "/terms", label: "Terms" },
  { href: "/legal", label: "Legal" },
  { href: "/copyrights", label: "Copyrights" },
  { href: "/api-documentation", label: "API Docs" },
  { href: "/neural-engine", label: "Neural Engine" },
  { href: "/strata-design-system", label: "Design System" },
  { href: "/lexicon-pro", label: "Lexicon Pro" },
  { href: "/voice-to-json", label: "Voice to JSON" },
  { href: "/geological-studies", label: "Geological Studies" },
  { href: "/admin/login.html", label: "Admin Login" },
];
