export interface NavigationItem {
  href: string;
  label: string;
}

export const SHARED_NAV_ITEMS: NavigationItem[] = [
  { href: "/", label: "Home" },
  { href: "/features", label: "Features" },
  { href: "/how-it-works", label: "How It Works" },
  { href: "/demo", label: "Demo" },
  { href: "/pricing", label: "Pricing" },
  { href: "/store", label: "Store" },
  { href: "/appstore", label: "App Store" },
  { href: "/appstore-new", label: "App Store New" },
  { href: "/admin/login", label: "Admin Login" },
  { href: "/blog", label: "Blog" },
  { href: "/cyber-blog", label: "Cyber Blog" },
  { href: "/livestream", label: "Live" },
  { href: "/support", label: "Support" },
  { href: "/contact", label: "Contact" },
  { href: "/about", label: "About" },
  { href: "/status", label: "Status" },
  { href: "/search", label: "Search" },
  { href: "/gallery", label: "Gallery" },
  { href: "/templates", label: "Templates" },
  { href: "/seo-template", label: "SEO Template" },
  { href: "/partners", label: "Partners" },
  { href: "/trust", label: "Trust Center" },
  { href: "/referrals", label: "Referrals" },
  { href: "/projects", label: "Projects" },
  { href: "/project-planning-hub", label: "Project Planning Hub" },
  { href: "/the3000", label: "The3000" },
  { href: "/the3000-gallery", label: "The3000 Gallery" },
  { href: "/studio3000", label: "Studio3000" },
  { href: "/webforge", label: "Webforge" },
  { href: "/cursor-demo", label: "Cursor Demo" },
  { href: "/sandbox", label: "Sandbox" },
  { href: "/color-synth", label: "Color Synth" },
  { href: "/focus-timer", label: "Focus Timer" },
  { href: "/memory-matrix", label: "Memory Matrix" },
  { href: "/neon-snake", label: "Neon Snake" },
  { href: "/zen-particles", label: "Zen Particles" },
  { href: "/rush-percussion", label: "Rush Percussion" },
  { href: "/stripe-connect-dashboard", label: "Stripe Dashboard" },
  { href: "/stripe-connect-storefront", label: "Stripe Storefront" },
  { href: "/disclosure", label: "Disclosure" },
  { href: "/license", label: "License" },
  { href: "/privacy", label: "Privacy" },
  { href: "/terms", label: "Terms" },
  { href: "/legal", label: "Legal" },
  { href: "/copyrights", label: "Copyrights" },
  { href: "/api-documentation", label: "API Docs" },
  { href: "/neural-engine", label: "Neural Engine" },
  { href: "/strata-design-system", label: "Design System" },
  { href: "/lexicon-pro", label: "Lexicon Pro" },
  { href: "/voice-to-json", label: "Voice to JSON" },
  { href: "/geological-studies", label: "Geological Studies" },
];
