import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Badge } from '@/components/ui/badge';
import { Calendar, Clock, ArrowRight, Play } from 'lucide-react';
import { Link } from 'react-router-dom';
import { TechStoryService, Story } from '@/lib/techStoryService';
import { GoogleAdSense } from '@/components/GoogleAdSense';
import { SplitLink } from '@/components/ui/SplitLink';
import { FizzyButton } from '@/components/ui/FizzyButton';
import { useNavigate } from 'react-router-dom';

export const Stories = () => {
  const [stories, setStories] = useState<Story[]>([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchStories = async () => {
      try {
        // Trigger check/generate
        await TechStoryService.checkAndGenerateStory();
        const data = await TechStoryService.getAllStories();
        setStories(data);
      } catch (err) {
        console.error("Failed to fetch stories", err);
      } finally {
        setLoading(false);
      }
    };

    fetchStories();
    const interval = setInterval(fetchStories, 5 * 60 * 1000);
    return () => clearInterval(interval);
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-12 h-12 border-4 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin" />
      </div>
    );
  }

  const latestStory = stories[0];
  const previousStories = stories.slice(1);

  return (
    <div className="pt-32 pb-40 px-6 max-w-7xl mx-auto">
      <div className="mb-20 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
        <div>
          <motion.h1 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="text-5xl md:text-8xl font-black text-white mb-6 tracking-tighter uppercase italic"
          >
            TECH <span className="text-indigo-400">STORIES</span>
          </motion.h1>
          <p className="text-slate-400 text-xl max-w-2xl font-medium leading-relaxed italic opacity-60">
            Hourly insights generated by Neural Aura. Experience the intersection of voice architecture and AI creation.
          </p>
        </div>
        <div className="relative aspect-video rounded-3xl overflow-hidden border border-white/10 shadow-2xl">
          <video src="https://assets.mixkit.co/videos/preview/mixkit-circuit-board-animation-9998-large.mp4" autoPlay loop muted playsInline className="w-full h-full object-cover" />
          <div className="absolute inset-0 bg-indigo-500/10 mix-blend-overlay" />
        </div>
      </div>

      <GoogleAdSense slot="stories-top" />

      {latestStory && (
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-32"
        >
          <div className="bg-white/[0.02] border border-white/5 rounded-3xl overflow-hidden group hover:border-white/10 transition-all">
            <div className="grid grid-cols-1 lg:grid-cols-2">
              <div className="relative h-[400px] lg:h-auto overflow-hidden">
                <video src={latestStory.videoUrl} autoPlay loop muted playsInline className="w-full h-full object-cover grayscale group-hover:grayscale-0 transition-all duration-1000" />
                <div className="absolute inset-0 bg-black/40 flex items-center justify-center">
                  <Link to={`/stories/${latestStory.id}`} className="w-20 h-20 bg-indigo-600 flex items-center justify-center group-hover:scale-110 transition-transform cursor-pointer shadow-lg">
                    <Play className="text-white fill-white ml-1" size={32} />
                  </Link>
                </div>
                <div className="absolute top-6 left-6">
                  <Badge className="bg-indigo-600 text-white px-4 py-1 text-xs font-black uppercase tracking-widest rounded-none border-none">LATEST STORY</Badge>
                </div>
              </div>
              <div className="p-12 flex flex-col justify-center">
                <div className="flex items-center gap-4 text-slate-500 mb-6 text-[10px] font-black uppercase tracking-widest italic">
                  <span className="flex items-center gap-1.5"><Calendar size={14} /> {latestStory.timestamp.toDate().toLocaleDateString()}</span>
                  <span className="flex items-center gap-1.5"><Clock size={14} /> {latestStory.timestamp.toDate().toLocaleTimeString()}</span>
                </div>
                <h2 className="text-4xl md:text-5xl font-black text-white mb-6 leading-tight uppercase italic tracking-tighter">{latestStory.title}</h2>
                <p className="text-slate-400 text-lg leading-relaxed mb-8 line-clamp-3 font-medium">
                  {latestStory.content}
                </p>
                <div className="pt-6">
                  <FizzyButton 
                    label="Witness Full Manifesto" 
                    onClick={() => navigate(`/stories/${latestStory.id}`)}
                    className="w-full lg:w-fit"
                  />
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {previousStories.map((story, i) => (
          <motion.div
            key={story.id}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.1 }}
          >
            <div className="bg-white/[0.02] border border-white/5 h-full flex flex-col group rounded-3xl hover:border-white/10 transition-all overflow-hidden">
              <div className="relative h-48 overflow-hidden border-b border-white/5">
                <video src={story.videoUrl} autoPlay loop muted playsInline className="w-full h-full object-cover grayscale group-hover:grayscale-0 transition-all duration-500" />
              </div>
              <div className="p-8 flex-1 flex flex-col">
                <div className="flex items-center gap-3 text-slate-500 mb-4 text-[9px] font-black uppercase tracking-widest italic">
                  <span className="flex items-center gap-1"><Calendar size={12} /> {story.timestamp.toDate().toLocaleDateString()}</span>
                </div>
                <h3 className="text-2xl font-black text-white mb-4 line-clamp-2 group-hover:text-indigo-400 transition-colors uppercase italic tracking-tighter">
                  {story.title}
                </h3>
                <Link to={`/stories/${story.id}`} className="mt-auto pt-6 border-t border-white/5 flex items-center justify-between group-hover:border-indigo-500/50 transition-colors">
                  <SplitLink className="text-indigo-400 text-[10px] font-black uppercase tracking-widest italic group-hover:gap-2 transition-all">
                    Unlock Manifesto
                  </SplitLink>
                </Link>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      <div className="mt-32">
        <GoogleAdSense slot="stories-bottom" />
      </div>
    </div>
  );
};
